# https://taskfile.dev

version: '3'

vars:
  GO_LDFLAGS: '-ldflags "-s -w"'

tasks:
  lbcli:
    dir: lbcli
    cmds:
      - task: c-ffi-v2
      - task: go-fmt
      - go build {{.GO_LDFLAGS}}
      - task: go-lint

  lbedit:
    dir: lbedit
    cmds:
      - task: c-ffi-v2
      - task: go-fmt
      - go build {{.GO_LDFLAGS}}
      - task: go-lint

  go-fmt:
    - goimports -w -l .
    - gofumpt -w -l .

  go-lint:
    - go vet ./...

  c-ffi-v2:
    dir: c_interface_v2
    vars:
      C_INTERFACE: src/lib.rs
      HEADER: lockbook_core.h
    cmds:
      - task: rust-fmt
      - cargo build -q --release
      - cbindgen {{.C_INTERFACE}} --config ./cbindgen.toml > ../{{.HEADER}}
      - task: rust-lint

  lbcli-rs:
    - task: rust-fmt
    - cargo build -p lbcli-rs -q --release
    - task: rust-lint

  rust-fmt:
    - cargo fmt --all --message-format short

  rust-lint:
    - cargo clippy -q --workspace
