# https://taskfile.dev

version: '3'

vars:
  GO_LDFLAGS: '-ldflags "-w"'
  C_INTERFACE_LIB: target/release/libc_interface_v2.a
  C_INTERFACE_HEADER: lockbook_core.h

tasks:
  lbcli:
    dir: lbcli
    cmds:
      - task: c-ffi-v2
      - task: go-fmt
      - go build {{.GO_LDFLAGS}}
      - task: go-lint

  lbcli-install:
    dir: lbcli
    cmds:
      - task: lbcli
      - cp ./lbcli ~/.local/bin

  lbgui:
    dir: lbgui
    cmds:
      - task: c-ffi-v2
      - task: go-fmt
      - go build -tags noopengl {{.GO_LDFLAGS}}
      - task: go-lint

  go-fmt:
    - goimports -w -l .
    - gofumpt -w -l .

  go-lint:
    - go vet ./...

  c-ffi-v2:
    dir: c_interface_v2
    cmds:
      - task: rust-fmt
      - cargo build -q --release
      - cbindgen src/lib.rs --config cbindgen.toml > ../{{.C_INTERFACE_HEADER}}
      - task: rust-lint
    sources:
      - ../lockbook/libs/**/*
      - ./**
      - cbindgen.toml
    generates:
      - ../{{.C_INTERFACE_LIB}}
      - ../{{.C_INTERFACE_HEADER}}

  rust-fmt:
    - cargo fmt --all --message-format short

  rust-lint:
    - cargo clippy -q --workspace
