[package]
name = "c_interface_v2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
lockbook-core = { path = "../lockbook/libs/core" }
libc = "0.2.139"
